### ISSUE TITLE
type must be either an array or a string.

### ISSUE THREAD

**Issue by itaimoorali** [snowyu/loopback-component-remote-ctx.js#2]
Hello there, I have integrated this component in my app.
I have encountered this issue when I define a custom remote method.
```
AssertionError [ERR_ASSERTION]: type must be either an array or a string.
    at TypeRegistry.getConverter (/home/taimurali/blue-east-projects/mevris-cloud-2/node_modules/strong-remoting/lib/type-registry.js:83:3)
    at HttpContext.buildArgs (/home/taimurali/blue-east-projects/mevris-cloud-2/node_modules/strong-remoting/lib/http-context.js:126:42)
    at new HttpContext (/home/taimurali/blue-east-projects/mevris-cloud-2/node_modules/strong-remoting/lib/http-context.js:59:20)
    at restStaticMethodHandler (/home/taimurali/blue-east-projects/mevris-cloud-2/node_modules/strong-remoting/lib/rest-adapter.js:485:15)
    at Layer.handle [as handle_request] (/home/taimurali/blue-east-projects/mevris-cloud-2/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/taimurali/blue-east-projects/mevris-cloud-2/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/taimurali/blue-east-projects/mevris-cloud-2/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/taimurali/blue-east-projects/mevris-cloud-2/node_modules/express/lib/router/layer.js:95:5)
    at /home/taimurali/blue-east-projects/mevris-cloud-2/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/taimurali/blue-east-projects/mevris-cloud-2/node_modules/express/lib/router/index.js:335:12)
    at next (/home/taimurali/blue-east-projects/mevris-cloud-2/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/taimurali/blue-east-projects/mevris-cloud-2/node_modules/express/lib/router/index.js:174:3)
    at router (/home/taimurali/blue-east-projects/mevris-cloud-2/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/taimurali/blue-east-projects/mevris-cloud-2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/taimurali/blue-east-projects/mevris-cloud-2/node_modules/express/lib/router/index.js:317:13)
    at /home/taimurali/blue-east-projects/mevris-cloud-2/node_modules/express/lib/router/index.js:284:7

```
When I debug the issue i found that this component is injecting an object into accepts array of remote method and it is of type **Object** which is causing the assertion test fail.
I don't know how to fix this. I have a way that I add my remoteMethod into blackList array of options of this component but i cant do that as i am using this along with [loopback-auditz](https://www.npmjs.com/package/loopback-auditz) and i want the remotectx instance on methods
please Help me out

**Comment by snowyu** [comment]
You should provide a simple demo repo to reproduce.

**Comment by itaimoorali** [comment]
Here is the link to sample repo.
https://github.com/taimoor736/loopback-remote-ctx-sample
run 
`npm install `
and start the server
`npm start`
and in browser go to `http://localhost:3000/explorer`
hit the Messages/greeting and try it out.
you will see the error

**Comment by snowyu** [comment]
Ok, I found it. just wait a few minutes to fix.

btw, there is a glitch on your sample:

```js
  //remember the options argument is always be injected
  Message.greet = function(options, cb) {
    //var cb = arguments[arguments.length-1]; //this should be better.
    cb(null, 'Hello, from the other side');
  };
  //or use promise
  Message.greet = function() {
    return Promise.resolve('Hello, from the other side');
  };


```

**Comment by snowyu** [comment]
done on 0.3.3

**Comment by itaimoorali** [comment]
Thank You @snowyu . Really appreciate. :+1:

**Comment by itaimoorali** [comment]
@snowyu  I want to ask you a question its not related to this issue but I am a bit confused about these statements of Loopback docs. can you please guide me 

> The current solution for context propagation in LoopBack has the following parts:
> 
> - Any additional context is passed in the “options” argument. Built-in methods such as PersistedModel.find or PersistedModel.create already accept this argument, custom user methods must be modified to accept it too.
>
> - Whenever a method invokes another method, the “options” argument must be passed down the invocation chain.
> 
> - To seed the “options” argument when a method is invoked via a REST call, the “options” argument must be annotated in remoting metadata with a specific value set in the “http” property.

Here [Using current Context](https://loopback.io/doc/en/lb3/Using-current-context.html).

Let say in my greeting method i am calling the user find method. like this.
```
  Message.greet = function(options, cb) {
    Message.app.models.User.find({where: {id: ""}}).then((res) => cb(null, res));
  };
```
But when i see this doc its only taking 2 params [Loopback Docs](https://apidocs.strongloop.com/loopback/#persistedmodel-find) filter and cb.

Can you please guide me.

**Comment by snowyu** [comment]
Yes, It does not be described in the docs.
```
Message.greet = function(options, cb) {
    Message.app.models.User.find({where: {id: ""}}, options).then((res) => cb(null, res));
  };
```

**Comment by itaimoorali** [comment]
Thank You so much. @snowyu
